GET http://localhost:4004/catalog/Authers

###

GET http://localhost:4004/catalog/Books?$expand=auther

###
POST  http://localhost:4004/catalog/Books
Content-Type: application/json

{"ID": 5, "title": "Test Post1", "stock": 10, "auther_ID": 123}

###

###
POST  http://localhost:4004/catalog/Authers
Content-Type: application/json

{"ID": 123, "name": "Sridhar Rajagopal"}
###